project:
  key: WEBCOM
  plan:
    name: webcomponent-renovate
    key: WC-REN
stages:
  - jobs:
      - scripts:
          - 'docker run --volume ${PWD}/renovate.json:/usr/src/app/renovate.json -e RENOVATE_TOKEN=955945622c6d758b064e9449c089988a5de4bbe8 -e RENOVATE_CONFIG_FILE=/usr/src/app/renovate.json renovate/renovate'
        requirements:
          - REMOTE_ONLY
